# Generated by Django 2.1.5 on 2019-06-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCourt',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('FID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_date', models.DateField()),
                ('item_name', models.CharField(max_length=500)),
                ('item_food_plan', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('item_foodcourt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.FoodCourt')),
            ],
        ),
    ]
