# Generated by Django 2.2.2 on 2019-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcourt', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_date', models.DateField()),
                ('item_name', models.CharField(max_length=500)),
                ('item_food_plan', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_foodcourt', models.CharField(default='Not Available', max_length=100)),
            ],
        ),
    ]
