# Generated by Django 2.1.5 on 2019-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='foodcourt',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='item_foodcourt',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
